#spring.application.name=Journal App
#spring.data.mongodb.host = localhost
#spring.data.mongodb.port = 27017
#spring.data.mongodb.database = journalDB
#spring.data.mongodb.auto-index-creation = true

#I dont have any username and password that's why I commented out this
#spring.data.mongodb.username = username
#spring.data.mongodb.password = password

#------------------------------------------------------------------------------------

#    Mongo db atlas
#    Username : workstack365_db_user
#    Password : AHLC1XcNwiybHVw3
#    mongodb+srv://workstack365_db_user:<db_password>@cluster0.ltalqrs.mongodb.net/?appName=Cluster0


##this information for connecting mongo db with aws server
#spring.data.mongodb.uri = mongodb+srv://workstack365_db_user:AHLC1XcNwiybHVw3@cluster0.ltalqrs.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database = journalDB
#spring.data.mongodb.auto-index-creation = true
#spring.main.allow-circular-references = true
#logging.level.org.springframework.security = DEBUG
#
##debug or high severity than debug
#logging.level.com.test.restProject = DEBUG
#
##this is for DEBUG from root level that from root package not just in rest project but this will just
##print DEBUG, INFO, WARN, ERROR nothing else not even that port number, starting that all things
##logging.level.root = ERROR
#
#
## this is data for weather api related
#weather-api-key = 91f61744b9e712f2c894c35ee0622cfb

#-------------------------------------------------------------------------------------------------------------
#all above configurations are from properties file

# this information for connecting mongo db with aws server
spring:
#  for kafka configuration
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: sentiment_data_analysis
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.test.restProject.entity
  data:
    redis:
#      this is for redis local machine
#      host: 127.0.0.1
#      port: 6379
      url: ${DATA_REDIS_URL}
    mongodb:
      uri: ${MONGODB_URL}
      database: journalDB
      auto-index-creation: true
  main:
    allow-circular-references: true
#  for sending email
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    org:
      springframework:
        security: DEBUG
    # debug or high severity than debug
    com:
      test:
        restProject: DEBUG
    # this is for DEBUG from root level that from root package not just in rest project but this will just
    # print DEBUG, INFO, WARN, ERROR nothing else not even that port number, starting that all things
    # logging.level.root: ERROR

# this is data for weather api related
weather-api-key: ${WEATHER_API_KEY}













